# Generated by Django 5.1.7 on 2025-04-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='city',
        ),
    ]
